# These are supported funding model platforms

github: # ['rappen'] 
custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=jonas@rappen.net&lc=EN&item_name=FetchXML+Builder+Fan+Club&currency_code=EUR&bn=PP-DonationsBF']
