version: '{build}'
branches:
  only:
  - noautobuilds
skip_tags: true
os: Visual Studio 2015
configuration: Release
init:
- ps: Update-AppveyorBuild -Version "1.$(Get-Date -format yyyy.M).$env:appveyor_build_number"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
after_build:
- 7z a FetchXMLBuilder_%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\FetchXMLBuilder\bin\%CONFIGURATION%\Cinteros.Xrm.*.dll
- appveyor PushArtifact FetchXMLBuilder_%APPVEYOR_BUILD_VERSION%.zip
deploy:
- provider: Environment
  name: GitHubFXB
- provider: FTP
  host: rappen.net
  protocol: ftp
  username: Jonas
  password:
    secure: tlAywufGDNedgIwqqBUmsA==
  folder: rappen/FXB
